# Generated by Django 4.0.6 on 2023-05-30 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='user',
        ),
        migrations.AddField(
            model_name='outcome',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
